FROM python:3.13-slim

RUN apt-get update -qq && \
    apt-get install -y ca-certificates --no-install-recommends -qq && \
    rm -rf /var/lib/apt/lists/*

COPY requirements_remote.txt .
RUN pip install --no-cache-dir -r requirements_remote.txt

WORKDIR /app
CMD ["python", "server_remote.py"]
