FROM python:3.13-slim

RUN apt-get update -qq && \
    apt-get install -y ca-certificates --no-install-recommends -qq && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir streamlit plotly pandas openpyxl pillow python-dotenv

WORKDIR /app
CMD ["streamlit", "run", "dashboard.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
