FROM python:3.13-slim

RUN apt-get update -qq && \
    apt-get install -y ca-certificates --no-install-recommends -qq && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir mcp python-dotenv uvicorn starlette

WORKDIR /app
CMD ["python", "server_remote.py"]
